# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craig Siemens
description: iOS Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://craigsiemens.com" # the base hostname & protocol for your site

twitter_username: CraigSiemens
github_username:  CraigSiemens

theme: jekyll-theme-slate

# Build settings
markdown: kramdown

collections:
  apps:
    title: "Apps"
    output: true
